services:
  frpc:
    image: snowdreamtech/frpc:alpine
    container_name: frpc
    restart: always
    volumes:
      - ./frpc.toml:/etc/frp/frpc.toml:ro

  caddy:
    image: caddy:alpine
    container_name: caddy
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
