services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    tty: true
    stdin_open: true
    restart: always
    ports:
      - 25565:25565
    volumes:
      - ./data:/data
    environment:
      EULA: "TRUE"
      EXEC_DIRECTLY: "true"
      # 保持以上的环境变量不变，
      # 以下的更多的环境变量见：
      # https://docker-minecraft-server.readthedocs.io/en/latest/variables/
      TYPE: "VANILLA"
      VERSION: "1.21.3"
      MEMORY: "2G"
      MAX_PLAYERS: "5"
      PVP: "false"
      ONLINE_MODE: "true"
      ALLOW_FLIGHT: "true"
      ENABLE_WHITELIST: "true"
